version: '3.7'
services:
  esignature:
    container_name: esignature
    build:
      context: ./
      target: development
    ports:
      - "8079:80"
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - monolith_network
      - monolith_internal
      - telemedi_nginx_proxy

  esignature_db:
    container_name: esignature_db
    image: postgres:13.3
    ports:
      - "4321:5432"
    environment:
      POSTGRES_DB: esignature_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - esignature_db_storage:/var/lib/postgresql/data
    networks:
      - monolith_network
      - monolith_internal

volumes:
  esignature_db_storage:
    driver: local

networks:
  monolith_internal:
    internal: true
  monolith_network:
    name: monolith_network
    driver: bridge
  telemedi_nginx_proxy:
    external:
      name: nginx-proxy
