api_platform:
    title: 'Digital Signature'
    description: 'Api for Digital Signature'
    version: '0.1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/DigitalSignature/UI/Api/Model/']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
